<?php

namespace App\CommanFunctions;


class TimezoneData
{
    public static function getTimezone()
    {
        # code...

        return [

            ["time_zone" => 'Pacific/Honolulu', "time_zone_name" => '(GMT-10:00) Hawaii Time'],
            ["time_zone" => 'America/Anchorage', "time_zone_name" => '(GMT-8:00) Alaska Time'],
            ["time_zone" => 'America/Los_Angeles', "time_zone_name" => '(GMT-7:00) Pacific Time'],
            ["time_zone" => 'America/Denver', "time_zone_name" => '(GMT-6:00) Mountain Time'],
            ["time_zone" => 'America/Phoenix', "time_zone_name" => '(GMT-7:00) Arizona Time'],
            ["time_zone" => 'America/Chicago', "time_zone_name" => '(GMT-5:00) Central Time'],
            ["time_zone" => 'America/New_York', "time_zone_name" => '(GMT-4:00) Eastern Time'],
            ["time_zone" => 'Pacific/Apia', "time_zone_name" => '(GMT+13:00) Apia'],
            ["time_zone" => 'Pacific/Midway', "time_zone_name" => '(GMT-11:00) Midway'],
            ["time_zone" => 'Pacific/Niue', "time_zone_name" => '(GMT-11:00) Niue'],
            ["time_zone" => 'Pacific/Pago_Pago', "time_zone_name" => '(GMT-11:00) Pago Pago'],
            ["time_zone" => 'Pacific/Fakaofo', "time_zone_name" => '(GMT+13:00) Fakaofo'],
            ["time_zone" => 'Pacific/Johnston', "time_zone_name" => '(GMT-10:00) Johnston'],
            ["time_zone" => 'Pacific/Rarotonga', "time_zone_name" => '(GMT-10:00) Rarotonga'],
            ["time_zone" => 'Pacific/Tahiti', "time_zone_name" => '(GMT-10:00) Tahiti'],
            ["time_zone" => 'Pacific/Marquesas', "time_zone_name" => '(GMT-9:30) Marquesas'],
            ["time_zone" => 'Pacific/Gambier', "time_zone_name" => '(GMT-9:00) Gambier'],
            ["time_zone" => 'America/Tijuana', "time_zone_name" => '(GMT-7:00) Pacific Time - Tijuana'],
            ["time_zone" => 'America/Vancouver', "time_zone_name" => '(GMT-7:00) Pacific Time - Vancouver'],
            ["time_zone" => 'Pacific/Pitcairn', "time_zone_name" => '(GMT-8:00) Pitcairn'],
            ["time_zone" => 'America/Dawson_Creek', "time_zone_name" => '(GMT-7:00) Mountain Time - Dawson Creek'],
            ["time_zone" => 'America/Edmonton', "time_zone_name" => '(GMT-6:00) Mountain Time - Edmonton'],
            ["time_zone" => 'America/Hermosillo', "time_zone_name" => '(GMT-7:00) Mountain Time - Hermosillo'],
            ["time_zone" => 'America/Mazatlan', "time_zone_name" => '(GMT-6:00) Mountain Time - Chihuahua, Mazatlan'],
            ["time_zone" => 'America/Whitehorse', "time_zone_name" => '(GMT-7:00) Mountain Time - Whitehorse'],
            ["time_zone" => 'America/Yellowknife', "time_zone_name" => '(GMT-6:00) Mountain Time - Yellowknife'],
            ["time_zone" => 'America/Belize', "time_zone_name" => '(GMT-6:00) Belize'],
            ["time_zone" => 'America/Costa_Rica', "time_zone_name" => '(GMT-6:00) Costa Rica'],
            ["time_zone" => 'America/El_Salvador', "time_zone_name" => '(GMT-6:00) El Salvador'],
            ["time_zone" => 'America/Guatemala', "time_zone_name" => '(GMT-6:00) Guatemala'],
            ["time_zone" => 'America/Managua', "time_zone_name" => '(GMT-6:00) Managua'],
            ["time_zone" => 'America/Mexico_City', "time_zone_name" => '(GMT-5:00) Central Time - Mexico City'],
            ["time_zone" => 'America/Regina', "time_zone_name" => '(GMT-6:00) Central Time - Regina'],
            ["time_zone" => 'America/Tegucigalpa', "time_zone_name" => '(GMT-6:00) Central Time - Tegucigalpa (no DST)'],
            ["time_zone" => 'America/Winnipeg', "time_zone_name" => '(GMT-5:00) Central Time - Winnipeg'],
            ["time_zone" => 'Pacific/Easter', "time_zone_name" => '(GMT-6:00) Easter Island'],
            ["time_zone" => 'Pacific/Galapagos', "time_zone_name" => '(GMT-6:00) Galapagos'],
            ["time_zone" => 'America/Bogota', "time_zone_name" => '(GMT-5:00) Bogota'],
            ["time_zone" => 'America/Cayman', "time_zone_name" => '(GMT-5:00) Cayman'],
            ["time_zone" => 'America/Grand_Turk', "time_zone_name" => '(GMT-4:00) Grand Turk'],
            ["time_zone" => 'America/Guayaquil', "time_zone_name" => '(GMT-5:00) Guayaquil'],
            ["time_zone" => 'America/Havana', "time_zone_name" => '(GMT-4:00) Havana'],
            ["time_zone" => 'America/Iqaluit', "time_zone_name" => '(GMT-4:00) Eastern Time - Iqaluit'],
            ["time_zone" => 'America/Jamaica', "time_zone_name" => '(GMT-5:00) Jamaica'],
            ["time_zone" => 'America/Lima', "time_zone_name" => '(GMT-5:00) Lima'],
            ["time_zone" => 'America/Cancun', "time_zone_name" => '(GMT-5:00) Cancun - Eastern Time - Quintana Roo'],
            ["time_zone" => 'America/Nassau', "time_zone_name" => '(GMT-4:00) Nassau'],
            ["time_zone" => 'America/Panama', "time_zone_name" => '(GMT-5:00) Panama'],
            ["time_zone" => 'America/Port-au-Prince', "time_zone_name" => '(GMT-4:00) Port-au-Prince'],
            ["time_zone" => 'America/Toronto', "time_zone_name" => '(GMT-4:00) Eastern Time - Toronto'],
            ["time_zone" => 'America/Caracas', "time_zone_name" => '(GMT-4:00) Caracas'],
            ["time_zone" => 'America/Anguilla', "time_zone_name" => '(GMT-4:00) Anguilla'],
            ["time_zone" => 'America/Antigua', "time_zone_name" => '(GMT-4:00) Antigua'],
            ["time_zone" => 'America/Aruba', "time_zone_name" => '(GMT-4:00) Aruba'],
            ["time_zone" => 'America/Asuncion', "time_zone_name" => '(GMT-4:00) Asuncion'],
            ["time_zone" => 'America/Barbados', "time_zone_name" => '(GMT-4:00) Barbados'],
            ["time_zone" => 'America/Boa_Vista', "time_zone_name" => '(GMT-4:00) Boa Vista'],
            ["time_zone" => 'America/Campo_Grande', "time_zone_name" => '(GMT-4:00) Campo Grande'],
            ["time_zone" => 'America/Cuiaba', "time_zone_name" => '(GMT-4:00) Cuiaba'],
            ["time_zone" => 'America/Curacao', "time_zone_name" => '(GMT-4:00) Curacao'],
            ["time_zone" => 'America/Dominica', "time_zone_name" => '(GMT-4:00) Dominica'],
            ["time_zone" => 'America/Grenada', "time_zone_name" => '(GMT-4:00) Grenada'],
            ["time_zone" => 'America/Guadeloupe', "time_zone_name" => '(GMT-4:00) Guadeloupe'],
            ["time_zone" => 'America/Guyana', "time_zone_name" => '(GMT-4:00) Guyana'],
            ["time_zone" => 'America/Halifax', "time_zone_name" => '(GMT-3:00) Atlantic Time - Halifax'],
            ["time_zone" => 'America/La_Paz', "time_zone_name" => '(GMT-4:00) La Paz'],
            ["time_zone" => 'America/Manaus', "time_zone_name" => '(GMT-4:00) Manaus'],
            ["time_zone" => 'America/Martinique', "time_zone_name" => '(GMT-4:00) Martinique'],
            ["time_zone" => 'America/Montserrat', "time_zone_name" => '(GMT-4:00) Montserrat'],
            ["time_zone" => 'America/Port_of_Spain', "time_zone_name" => '(GMT-4:00) Port of Spain'],
            ["time_zone" => 'America/Porto_Velho', "time_zone_name" => '(GMT-4:00) Porto Velho'],
            ["time_zone" => 'America/Puerto_Rico', "time_zone_name" => '(GMT-4:00) Puerto Rico'],
            ["time_zone" => 'America/Rio_Branco', "time_zone_name" => '(GMT-5:00) Rio Branco'],
            ["time_zone" => 'America/Santiago', "time_zone_name" => '(GMT-4:00) Santiago'],
            ["time_zone" => 'America/Santo_Domingo', "time_zone_name" => '(GMT-4:00) Santo Domingo'],
            ["time_zone" => 'America/St_Kitts', "time_zone_name" => '(GMT-4:00) St. Kitts'],
            ["time_zone" => 'America/St_Lucia', "time_zone_name" => '(GMT-4:00) St. Lucia'],
            ["time_zone" => 'America/St_Thomas', "time_zone_name" => '(GMT-4:00) St. Thomas'],
            ["time_zone" => 'America/St_Vincent', "time_zone_name" => '(GMT-4:00) St. Vincent'],
            ["time_zone" => 'America/Thule', "time_zone_name" => '(GMT-3:00) Thule'],
            ["time_zone" => 'America/Tortola', "time_zone_name" => '(GMT-4:00) Tortola'],
            ["time_zone" => 'Antarctica/Palmer', "time_zone_name" => '(GMT-3:00) Palmer'],
            ["time_zone" => 'Atlantic/Bermuda', "time_zone_name" => '(GMT-3:00) Bermuda'],
            ["time_zone" => 'Atlantic/Stanley', "time_zone_name" => '(GMT-3:00) Stanley'],
            ["time_zone" => 'America/St_Johns', "time_zone_name" => '(GMT-2:30) Newfoundland Time - St. Johns'],
            ["time_zone" => 'America/Araguaina', "time_zone_name" => '(GMT-3:00) Araguaina'],
            ["time_zone" => 'America/Argentina/Buenos_Aires', "time_zone_name" => '(GMT-3:00) Buenos Aires'],
            ["time_zone" => 'America/Bahia', "time_zone_name" => '(GMT-3:00) Salvador'],
            ["time_zone" => 'America/Belem', "time_zone_name" => '(GMT-3:00) Belem'],
            ["time_zone" => 'America/Cayenne', "time_zone_name" => '(GMT-3:00) Cayenne'],
            ["time_zone" => 'America/Fortaleza', "time_zone_name" => '(GMT-3:00) Fortaleza'],
            ["time_zone" => 'America/Godthab', "time_zone_name" => '(GMT-2:00) Godthab'],
            ["time_zone" => 'America/Maceio', "time_zone_name" => '(GMT-3:00) Maceio'],
            ["time_zone" => 'America/Miquelon', "time_zone_name" => '(GMT-2:00) Miquelon'],
            ["time_zone" => 'America/Montevideo', "time_zone_name" => '(GMT-3:00) Montevideo'],
            ["time_zone" => 'America/Paramaribo', "time_zone_name" => '(GMT-3:00) Paramaribo'],
            ["time_zone" => 'America/Recife', "time_zone_name" => '(GMT-3:00) Recife'],
            ["time_zone" => 'America/Sao_Paulo', "time_zone_name" => '(GMT-3:00) Sao Paulo'],
            ["time_zone" => 'Antarctica/Rothera', "time_zone_name" => '(GMT-3:00) Rothera'],
            ["time_zone" => 'America/Noronha', "time_zone_name" => '(GMT-2:00) Noronha'],
            ["time_zone" => 'Atlantic/South_Georgia', "time_zone_name" => '(GMT-2:00) South Georgia'],
            ["time_zone" => 'America/Scoresbysund', "time_zone_name" => '(GMT+0:00) Scoresbysund'],
            ["time_zone" => 'Atlantic/Azores', "time_zone_name" => '(GMT+0:00) Azores'],
            ["time_zone" => 'Atlantic/Cape_Verde', "time_zone_name" => '(GMT-1:00) Cape Verde'],
            ["time_zone" => 'Africa/Abidjan', "time_zone_name" => '(GMT+0:00) Abidjan'],
            ["time_zone" => 'Africa/Accra', "time_zone_name" => '(GMT+0:00) Accra'],
            ["time_zone" => 'Africa/Bamako', "time_zone_name" => '(GMT+0:00) Bamako'],
            ["time_zone" => 'Africa/Banjul', "time_zone_name" => '(GMT+0:00) Banjul'],
            ["time_zone" => 'Africa/Bissau', "time_zone_name" => '(GMT+0:00) Bissau'],
            ["time_zone" => 'Africa/Casablanca', "time_zone_name" => '(GMT+1:00) Casablanca'],
            ["time_zone" => 'Africa/Conakry', "time_zone_name" => '(GMT+0:00) Conakry'],
            ["time_zone" => 'Africa/Dakar', "time_zone_name" => '(GMT+0:00) Dakar'],
            ["time_zone" => 'Africa/El_Aaiun', "time_zone_name" => '(GMT+1:00) El Aaiun'],
            ["time_zone" => 'Africa/Freetown', "time_zone_name" => '(GMT+0:00) Freetown'],
            ["time_zone" => 'Africa/Lome', "time_zone_name" => '(GMT+0:00) Lome'],
            ["time_zone" => 'Africa/Monrovia', "time_zone_name" => '(GMT+0:00) Monrovia'],
            ["time_zone" => 'Africa/Nouakchott', "time_zone_name" => '(GMT+0:00) Nouakchott'],
            ["time_zone" => 'Africa/Ouagadougou', "time_zone_name" => '(GMT+0:00) Ouagadougou'],
            ["time_zone" => 'Africa/Sao_Tome', "time_zone_name" => '(GMT+0:00) Sao Tome'],
            ["time_zone" => 'America/Danmarkshavn', "time_zone_name" => '(GMT+0:00) Danmarkshavn'],
            ["time_zone" => 'Atlantic/Canary', "time_zone_name" => '(GMT+1:00) Canary Islands'],
            ["time_zone" => 'Atlantic/Faroe', "time_zone_name" => '(GMT+1:00) Faeroe'],
            ["time_zone" => 'Atlantic/Reykjavik', "time_zone_name" => '(GMT+0:00) Reykjavik'],
            ["time_zone" => 'Atlantic/St_Helena', "time_zone_name" => '(GMT+0:00) St Helena'],
            ["time_zone" => 'Etc/GMT', "time_zone_name" => '(GMT+0:00) GMT (no daylight saving'],
            ["time_zone" => 'Europe/Dublin', "time_zone_name" => '(GMT+1:00) Dublin'],
            ["time_zone" => 'Europe/Lisbon', "time_zone_name" => '(GMT+1:00) Lisbon'],
            ["time_zone" => 'Europe/London', "time_zone_name" => '(GMT+1:00) London'],
            ["time_zone" => 'Africa/Algiers', "time_zone_name" => '(GMT+1:00) Algiers'],
            ["time_zone" => 'Africa/Bangui', "time_zone_name" => '(GMT+1:00) Bangui'],
            ["time_zone" => 'Africa/Brazzaville', "time_zone_name" => '(GMT+1:00) Brazzaville'],
            ["time_zone" => 'Africa/Ceuta', "time_zone_name" => '(GMT+2:00) Ceuta'],
            ["time_zone" => 'Africa/Douala', "time_zone_name" => '(GMT+1:00) Douala'],
            ["time_zone" => 'Africa/Kinshasa', "time_zone_name" => '(GMT+1:00) Kinshasa'],
            ["time_zone" => 'Africa/Lagos', "time_zone_name" => '(GMT+1:00) Lagos'],
            ["time_zone" => 'Africa/Libreville', "time_zone_name" => '(GMT+1:00) Libreville'],
            ["time_zone" => 'Africa/Luanda', "time_zone_name" => '(GMT+1:00) Luanda'],
            ["time_zone" => 'Africa/Malabo', "time_zone_name" => '(GMT+1:00) Malabo'],
            ["time_zone" => 'Africa/Ndjamena', "time_zone_name" => '(GMT+1:00) Ndjamena'],
            ["time_zone" => 'Africa/Niamey', "time_zone_name" => '(GMT+1:00) Niamey'],
            ["time_zone" => 'Africa/Porto-Novo', "time_zone_name" => '(GMT+1:00) Porto-Novo'],
            ["time_zone" => 'Africa/Tunis', "time_zone_name" => '(GMT+1:00) Tunis'],
            ["time_zone" => 'Africa/Windhoek', "time_zone_name" => '(GMT+2:00) Windhoek'],
            ["time_zone" => 'Europe/Amsterdam', "time_zone_name" => '(GMT+2:00) Amsterdam'],
            ["time_zone" => 'Europe/Andorra', "time_zone_name" => '(GMT+2:00) Andorra'],
            ["time_zone" => 'Europe/Belgrade', "time_zone_name" => '(GMT+2:00) Central European Time (Europe/Belgrade'],
            ["time_zone" => 'Europe/Berlin', "time_zone_name" => '(GMT+2:00) Berlin'],
            ["time_zone" => 'Europe/Brussels', "time_zone_name" => '(GMT+2:00) Brussels'],
            ["time_zone" => 'Europe/Budapest', "time_zone_name" => '(GMT+2:00) Budapest'],
            ["time_zone" => 'Europe/Copenhagen', "time_zone_name" => '(GMT+2:00) Copenhagen'],
            ["time_zone" => 'Europe/Gibraltar', "time_zone_name" => '(GMT+2:00) Gibraltar'],
            ["time_zone" => 'Europe/Luxembourg', "time_zone_name" => '(GMT+2:00) Luxembourg'],
            ["time_zone" => 'Europe/Madrid', "time_zone_name" => '(GMT+2:00) Madrid'],
            ["time_zone" => 'Europe/Malta', "time_zone_name" => '(GMT+2:00) Malta'],
            ["time_zone" => 'Europe/Monaco', "time_zone_name" => '(GMT+2:00) Monaco'],
            ["time_zone" => 'Europe/Oslo', "time_zone_name" => '(GMT+2:00) Oslo'],
            ["time_zone" => 'Europe/Paris', "time_zone_name" => '(GMT+2:00) Paris'],
            ["time_zone" => 'Europe/Prague', "time_zone_name" => '(GMT+2:00) Central European Time (Europe/Prague'],
            ["time_zone" => 'Europe/Rome', "time_zone_name" => '(GMT+2:00) Rome'],
            ["time_zone" => 'Europe/Stockholm', "time_zone_name" => '(GMT+2:00) Stockholm'],
            ["time_zone" => 'Europe/Tirane', "time_zone_name" => '(GMT+2:00) Tirane'],
            ["time_zone" => 'Europe/Vaduz', "time_zone_name" => '(GMT+2:00) Vaduz'],
            ["time_zone" => 'Europe/Vienna', "time_zone_name" => '(GMT+2:00) Vienna'],
            ["time_zone" => 'Europe/Warsaw', "time_zone_name" => '(GMT+2:00) Warsaw'],
            ["time_zone" => 'Europe/Zurich', "time_zone_name" => '(GMT+2:00) Zurich'],
            ["time_zone" => 'Africa/Blantyre', "time_zone_name" => '(GMT+2:00) Blantyre'],
            ["time_zone" => 'Africa/Bujumbura', "time_zone_name" => '(GMT+2:00) Bujumbura'],
            ["time_zone" => 'Africa/Cairo', "time_zone_name" => '(GMT+2:00) Cairo'],
            ["time_zone" => 'Africa/Gaborone', "time_zone_name" => '(GMT+2:00) Gaborone'],
            ["time_zone" => 'Africa/Harare', "time_zone_name" => '(GMT+2:00) Harare'],
            ["time_zone" => 'Africa/Johannesburg', "time_zone_name" => '(GMT+2:00) Johannesburg'],
            ["time_zone" => 'Africa/Kigali', "time_zone_name" => '(GMT+2:00) Kigali'],
            ["time_zone" => 'Africa/Lubumbashi', "time_zone_name" => '(GMT+2:00) Lubumbashi'],
            ["time_zone" => 'Africa/Lusaka', "time_zone_name" => '(GMT+2:00) Lusaka'],
            ["time_zone" => 'Africa/Maputo', "time_zone_name" => '(GMT+2:00) Maputo'],
            ["time_zone" => 'Africa/Maseru', "time_zone_name" => '(GMT+2:00) Maseru'],
            ["time_zone" => 'Africa/Mbabane', "time_zone_name" => '(GMT+2:00) Mbabane'],
            ["time_zone" => 'Africa/Tripoli', "time_zone_name" => '(GMT+2:00) Tripoli'],
            ["time_zone" => 'Asia/Amman', "time_zone_name" => '(GMT+3:00) Amman'],
            ["time_zone" => 'Asia/Beirut', "time_zone_name" => '(GMT+3:00) Beirut'],
            ["time_zone" => 'Asia/Damascus', "time_zone_name" => '(GMT+3:00) Damascus'],
            ["time_zone" => 'Asia/Gaza', "time_zone_name" => '(GMT+3:00) Gaza'],
            ["time_zone" => 'Asia/Jerusalem', "time_zone_name" => '(GMT+3:00) Jerusalem'],
            ["time_zone" => 'Asia/Nicosia', "time_zone_name" => '(GMT+3:00) Nicosia'],
            ["time_zone" => 'Europe/Athens', "time_zone_name" => '(GMT+3:00) Athens'],
            ["time_zone" => 'Europe/Bucharest', "time_zone_name" => '(GMT+3:00) Bucharest'],
            ["time_zone" => 'Europe/Chisinau', "time_zone_name" => '(GMT+3:00) Chisinau'],
            ["time_zone" => 'Europe/Helsinki', "time_zone_name" => '(GMT+3:00) Helsinki'],
            ["time_zone" => 'Europe/Istanbul', "time_zone_name" => '(GMT+3:00) Istanbul'],
            ["time_zone" => 'Europe/Kaliningrad', "time_zone_name" => '(GMT+2:00) Russia - Kaliningrad'],
            ["time_zone" => 'Europe/Kiev', "time_zone_name" => '(GMT+3:00) Kyiv'],
            ["time_zone" => 'Europe/Minsk', "time_zone_name" => '(GMT+3:00) Minsk'],
            ["time_zone" => 'Europe/Riga', "time_zone_name" => '(GMT+3:00) Riga'],
            ["time_zone" => 'Europe/Sofia', "time_zone_name" => '(GMT+3:00) Sofia'],
            ["time_zone" => 'Europe/Tallinn', "time_zone_name" => '(GMT+3:00) Tallinn'],
            ["time_zone" => 'Europe/Vilnius', "time_zone_name" => '(GMT+3:00) Vilnius'],
            ["time_zone" => 'Africa/Addis_Ababa', "time_zone_name" => '(GMT+3:00) Addis Ababa'],
            ["time_zone" => 'Africa/Asmara', "time_zone_name" => '(GMT+3:00) Asmera'],
            ["time_zone" => 'Africa/Dar_es_Salaam', "time_zone_name" => '(GMT+3:00) Dar es Salaam'],
            ["time_zone" => 'Africa/Djibouti', "time_zone_name" => '(GMT+3:00) Djibouti'],
            ["time_zone" => 'Africa/Kampala', "time_zone_name" => '(GMT+3:00) Kampala'],
            ["time_zone" => 'Africa/Khartoum', "time_zone_name" => '(GMT+2:00) Khartoum'],
            ["time_zone" => 'Africa/Mogadishu', "time_zone_name" => '(GMT+3:00) Mogadishu'],
            ["time_zone" => 'Africa/Nairobi', "time_zone_name" => '(GMT+3:00) Nairobi'],
            ["time_zone" => 'Antarctica/Syowa', "time_zone_name" => '(GMT+3:00) Syowa'],
            ["time_zone" => 'Asia/Aden', "time_zone_name" => '(GMT+3:00) Aden'],
            ["time_zone" => 'Asia/Baghdad', "time_zone_name" => '(GMT+3:00) Baghdad'],
            ["time_zone" => 'Asia/Bahrain', "time_zone_name" => '(GMT+3:00) Bahrain'],
            ["time_zone" => 'Asia/Kuwait', "time_zone_name" => '(GMT+3:00) Kuwait'],
            ["time_zone" => 'Asia/Qatar', "time_zone_name" => '(GMT+3:00) Qatar'],
            ["time_zone" => 'Asia/Riyadh', "time_zone_name" => '(GMT+3:00) Riyadh'],
            ["time_zone" => 'Europe/Moscow', "time_zone_name" => '(GMT+3:00) Russia - Moscow'],
            ["time_zone" => 'Indian/Antananarivo', "time_zone_name" => '(GMT+3:00) Antananarivo'],
            ["time_zone" => 'Indian/Comoro', "time_zone_name" => '(GMT+3:00) Comoro'],
            ["time_zone" => 'Indian/Mayotte', "time_zone_name" => '(GMT+3:00) Mayotte'],
            ["time_zone" => 'Asia/Tehran', "time_zone_name" => '(GMT+4:30) Tehran'],
            ["time_zone" => 'Asia/Baku', "time_zone_name" => '(GMT+4:00) Baku'],
            ["time_zone" => 'Asia/Dubai', "time_zone_name" => '(GMT+4:00) Dubai'],
            ["time_zone" => 'Asia/Muscat', "time_zone_name" => '(GMT+4:00) Muscat'],
            ["time_zone" => 'Asia/Tbilisi', "time_zone_name" => '(GMT+4:00) Tbilisi'],
            ["time_zone" => 'Asia/Yerevan', "time_zone_name" => '(GMT+4:00) Yerevan'],
            ["time_zone" => 'Europe/Samara', "time_zone_name" => '(GMT+4:00) Russia - Samara'],
            ["time_zone" => 'Indian/Mahe', "time_zone_name" => '(GMT+4:00) Mahe'],
            ["time_zone" => 'Indian/Mauritius', "time_zone_name" => '(GMT+4:00) Mauritius'],
            ["time_zone" => 'Indian/Reunion', "time_zone_name" => '(GMT+4:00) Reunion'],
            ["time_zone" => 'Asia/Kabul', "time_zone_name" => '(GMT+4:30) Kabul'],
            ["time_zone" => 'Asia/Aqtau', "time_zone_name" => '(GMT+5:00) Aqtau'],
            ["time_zone" => 'Asia/Aqtobe', "time_zone_name" => '(GMT+5:00) Aqtobe'],
            ["time_zone" => 'Asia/Ashgabat', "time_zone_name" => '(GMT+5:00) Ashgabat'],
            ["time_zone" => 'Asia/Dushanbe', "time_zone_name" => '(GMT+5:00) Dushanbe'],
            ["time_zone" => 'Asia/Karachi', "time_zone_name" => '(GMT+5:00) Karachi'],
            ["time_zone" => 'Asia/Tashkent', "time_zone_name" => '(GMT+5:00) Tashkent'],
            ["time_zone" => 'Asia/Yekaterinburg', "time_zone_name" => '(GMT+5:00) Russia - Yekaterinburg'],
            ["time_zone" => 'Indian/Kerguelen', "time_zone_name" => '(GMT+5:00) Kerguelen'],
            ["time_zone" => 'Indian/Maldives', "time_zone_name" => '(GMT+5:00) Maldives'],
            ["time_zone" => 'Asia/Kolkata', "time_zone_name" => '(GMT+5:30) India Standard Time'],
            ["time_zone" => 'Asia/Colombo', "time_zone_name" => '(GMT+5:30) Colombo'],
            ["time_zone" => 'Asia/Kathmandu', "time_zone_name" => '(GMT+5:45) Kathmandu'],
            ["time_zone" => 'Antarctica/Mawson', "time_zone_name" => '(GMT+5:00) Mawson'],
            ["time_zone" => 'Antarctica/Vostok', "time_zone_name" => '(GMT+6:00) Vostok'],
            ["time_zone" => 'Asia/Almaty', "time_zone_name" => '(GMT+6:00) Almaty'],
            ["time_zone" => 'Asia/Bishkek', "time_zone_name" => '(GMT+6:00) Bishkek'],
            ["time_zone" => 'Asia/Dhaka', "time_zone_name" => '(GMT+6:00) Dhaka'],
            ["time_zone" => 'Asia/Omsk', "time_zone_name" => '(GMT+6:00) Russia - Omsk'],
            ["time_zone" => 'Asia/Novosibirsk', "time_zone_name" => '(GMT+7:00) Russia - Novosibirsk'],
            ["time_zone" => 'Asia/Thimphu', "time_zone_name" => '(GMT+6:00) Thimphu'],
            ["time_zone" => 'Indian/Chagos', "time_zone_name" => '(GMT+6:00) Chagos'],
            ["time_zone" => 'Asia/Rangoon', "time_zone_name" => '(GMT+6:30) Rangoon'],
            ["time_zone" => 'Indian/Cocos', "time_zone_name" => '(GMT+6:30) Cocos'],
            ["time_zone" => 'Antarctica/Davis', "time_zone_name" => '(GMT+7:00) Davis'],
            ["time_zone" => 'Asia/Bangkok', "time_zone_name" => '(GMT+7:00) Bangkok'],
            ["time_zone" => 'Asia/Hovd', "time_zone_name" => '(GMT+7:00) Hovd'],
            ["time_zone" => 'Asia/Jakarta', "time_zone_name" => '(GMT+7:00) Jakarta'],
            ["time_zone" => 'Asia/Krasnoyarsk', "time_zone_name" => '(GMT+7:00) Russia - Krasnoyarsk'],
            ["time_zone" => 'Asia/Phnom_Penh', "time_zone_name" => '(GMT+7:00) Phnom Penh'],
            ["time_zone" => 'Asia/Ho_Chi_Minh', "time_zone_name" => '(GMT+7:00) Hanoi'],
            ["time_zone" => 'Asia/Vientiane', "time_zone_name" => '(GMT+7:00) Vientiane'],
            ["time_zone" => 'Indian/Christmas', "time_zone_name" => '(GMT+7:00) Christmas'],
            ["time_zone" => 'Antarctica/Casey', "time_zone_name" => '(GMT+11:00) Casey'],
            ["time_zone" => 'Asia/Brunei', "time_zone_name" => '(GMT+8:00) Brunei'],
            ["time_zone" => 'Asia/Choibalsan', "time_zone_name" => '(GMT+8:00) Choibalsan'],
            ["time_zone" => 'Asia/Hong_Kong', "time_zone_name" => '(GMT+8:00) Hong Kong'],
            ["time_zone" => 'Asia/Irkutsk', "time_zone_name" => '(GMT+8:00) Russia - Irkutsk'],
            ["time_zone" => 'Asia/Kuala_Lumpur', "time_zone_name" => '(GMT+8:00) Kuala Lumpur'],
            ["time_zone" => 'Asia/Macau', "time_zone_name" => '(GMT+8:00) Macau'],
            ["time_zone" => 'Asia/Makassar', "time_zone_name" => '(GMT+8:00) Makassar'],
            ["time_zone" => 'Asia/Manila', "time_zone_name" => '(GMT+8:00) Manila'],
            ["time_zone" => 'Asia/Shanghai', "time_zone_name" => '(GMT+8:00) China Time - Beijing'],
            ["time_zone" => 'Asia/Singapore', "time_zone_name" => '(GMT+8:00) Singapore'],
            ["time_zone" => 'Asia/Taipei', "time_zone_name" => '(GMT+8:00) Taipei'],
            ["time_zone" => 'Asia/Ulaanbaatar', "time_zone_name" => '(GMT+8:00) Ulaanbaatar'],
            ["time_zone" => 'Australia/Perth', "time_zone_name" => '(GMT+8:00) Western Time - Perth'],
            ["time_zone" => 'Asia/Dili', "time_zone_name" => '(GMT+9:00) Dili'],
            ["time_zone" => 'Asia/Jayapura', "time_zone_name" => '(GMT+9:00) Jayapura'],
            ["time_zone" => 'Asia/Pyongyang', "time_zone_name" => '(GMT+9:00) Pyongyang'],
            ["time_zone" => 'Asia/Seoul', "time_zone_name" => '(GMT+9:00) Seoul'],
            ["time_zone" => 'Asia/Tokyo', "time_zone_name" => '(GMT+9:00) Tokyo'],
            ["time_zone" => 'Asia/Yakutsk', "time_zone_name" => '(GMT+9:00) Russia - Yakutsk'],
            ["time_zone" => 'Pacific/Palau', "time_zone_name" => '(GMT+9:00) Palau'],
            ["time_zone" => 'Australia/Adelaide', "time_zone_name" => '(GMT+9:30) Central Time - Adelaide'],
            ["time_zone" => 'Australia/Darwin', "time_zone_name" => '(GMT+9:30) Central Time - Darwin'],
            ["time_zone" => 'Antarctica/DumontDUrville', "time_zone_name" => "(GMT+10:00) Dumont D'Urville"],
            ["time_zone" => 'Asia/Vladivostok', "time_zone_name" => '(GMT+10:00) Russia - Yuzhno-Sakhalinsk'],
            ["time_zone" => 'Australia/Brisbane', "time_zone_name" => '(GMT+10:00) Eastern Time - Brisbane'],
            ["time_zone" => 'Australia/Hobart', "time_zone_name" => '(GMT+10:00) Eastern Time - Hobart'],
            ["time_zone" => 'Australia/Sydney', "time_zone_name" => '(GMT+10:00) Eastern Time - Sydney'],
            ["time_zone" => 'Australia/Melbourne', "time_zone_name" => '(GMT+10:00) Eastern Time - Melbourne'],
            ["time_zone" => 'Pacific/Guam', "time_zone_name" => '(GMT+10:00) Guam'],
            ["time_zone" => 'Pacific/Port_Moresby', "time_zone_name" => '(GMT+10:00) Port Moresby'],
            ["time_zone" => 'Pacific/Saipan', "time_zone_name" => '(GMT+10:00) Saipan'],
            ["time_zone" => 'Pacific/Chuuk', "time_zone_name" => '(GMT+10:00) Chuuk'],
            ["time_zone" => 'Asia/Magadan', "time_zone_name" => '(GMT+11:00) Russia - Magadan'],
            ["time_zone" => 'Pacific/Efate', "time_zone_name" => '(GMT+11:00) Efate'],
            ["time_zone" => 'Pacific/Guadalcanal', "time_zone_name" => '(GMT+11:00) Guadalcanal'],
            ["time_zone" => 'Pacific/Kosrae', "time_zone_name" => '(GMT+11:00) Kosrae'],
            ["time_zone" => 'Pacific/Noumea', "time_zone_name" => '(GMT+11:00) Noumea'],
            ["time_zone" => 'Pacific/Pohnpei', "time_zone_name" => '(GMT+11:00) Pohnpei'],
            ["time_zone" => 'Pacific/Norfolk', "time_zone_name" => '(GMT+11:00) Norfolk'],
            ["time_zone" => 'Asia/Kamchatka', "time_zone_name" => '(GMT+12:00) Russia - Petropavlovsk-Kamchatskiy'],
            ["time_zone" => 'Pacific/Auckland', "time_zone_name" => '(GMT+12:00) Auckland'],
            ["time_zone" => 'Pacific/Fiji', "time_zone_name" => '(GMT+12:00) Fiji'],
            ["time_zone" => 'Pacific/Funafuti', "time_zone_name" => '(GMT+12:00) Funafuti'],
            ["time_zone" => 'Pacific/Kwajalein', "time_zone_name" => '(GMT+12:00) Kwajalein'],
            ["time_zone" => 'Pacific/Majuro', "time_zone_name" => '(GMT+12:00) Majuro'],
            ["time_zone" => 'Pacific/Nauru', "time_zone_name" => '(GMT+12:00) Nauru'],
            ["time_zone" => 'Pacific/Tarawa', "time_zone_name" => '(GMT+12:00) Tarawa'],
            ["time_zone" => 'Pacific/Wake', "time_zone_name" => '(GMT+12:00) Wake'],
            ["time_zone" => 'Pacific/Wallis', "time_zone_name" => '(GMT+12:00) Wallis'],
            ["time_zone" => 'Pacific/Enderbury', "time_zone_name" => '(GMT+13:00) Enderbury'],
            ["time_zone" => 'Pacific/Tongatapu', "time_zone_name" => '(GMT+13:00) Tongatapu'],
            ["time_zone" => 'Pacific/Kiritimati', "time_zone_name" => '(GMT+14:00) Kiritimati'],
        ];
    }
}
